name: C/C++ CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install harfbuzz
      run: sudo apt install -y libharfbuzz-dev
    - name: make install
      run: sudo make clean install
